# Site settings
title: Gumdrop Attack
email: gumdropattack@gmail.com
description: > # 
   iOS Mobile Arcade game.
   Just in time for the Holidays!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gumdropattack.com/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
